---
- name: Webserver setup
  hosts: workers
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes

- name: Database setup
  hosts: worker03
  become: yes
  vars:
    dbname: accounts
  tasks:
    - debug:
        msg: "Database name is {{ dbname }}"

    - debug:
        var: dbname

    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present
    
    - name: Install pymsysql
      yum:
        name: python3-PyMySQL
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    #install ansible community galaxy first

    - name: Create database
      community.mysql.mysql_db:
        name: "{{ dbname }}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: result

    - name: Create database user with 'vprofile'
      community.mysql.mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpass }}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Printing the result
      debug:
        var: result